[package]
name = "bt3_meta"
version = "0.1.0"
authors = ["Karl Hobley <karlhobley10@gmail.com>"]

[dependencies]
piston_window = "0.11.0"
cgmath = "0.2.0"
gfx = "0.6.5"

[dependencies.bt3]
path = "src/core"
version = "0.1.0"

[dependencies.bt3_render_gl]
path = "src/renderers/gl"
version = "0.1.0"
