[package]
name = "bt3"
version = "0.1.0"
authors = ["Karl Hobley <karlhobley10@gmail.com>"]

[[bin]]
name = "pistontest"
path = "src/pistontest.rs"

[dependencies]
image = "0.3.11"
gfx = "0.6.5"
vecmath = "0.1.1"
