[package]
name = "bt3_render_gl"
version = "0.1.0"
authors = ["Karl Hobley <karlhobley10@gmail.com>"]

[lib]
name = "bt3_render_gl"

[dependencies]
gfx = "0.6.5"
gfx_device_gl = "0.4.1"
genmesh = "0.2.1"

[dependencies.bt3]
path = "../../core"
version = "0.1.0"
